GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/5

###
GET http://localhost:3001/api/persons/delete/1

###
GET http://localhost:3001/api/persons/delete/5
