### get all person
GET https://mkk-phonebook.herokuapp.com/api/persons

### get info
GET https://mkk-phonebook.herokuapp.com/info

### find person with id=1
GET https://mkk-phonebook.herokuapp.com/api/persons/1

### find person with false id
GET https://mkk-phonebook.herokuapp.com/api/persons/5

### delete person with id=1
DELETE  https://mkk-phonebook.herokuapp.com/api/persons/1

### delete person with false id
GET https://mkk-phonebook.herokuapp.com/api/persons/5

### add person
POST https://mkk-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name":"Mg Mg",
    "number":"09-08-115599"
}

### add person without name
POST https://mkk-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "number":"09-08-115599"
}

### add person without number
POST https://mkk-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name":"Mg Mg"
}

### add person with name already exists
POST https://mkk-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name":"Arto Hellas",
    "number":"09-08-115599"
}